### ISSUE TITLE
renombramos renderView a renderItems?

### ISSUE THREAD

**Issue by unjust** [Laboratoria/impl-dev-data-lovers#18]
En feat/data-lovers hice esta cambio muy apurado a final, y no se si queremos quedar con eso ?
renombre renderView a renderItems porque renderView me suena como la vista entreo.
Que opinas @DeysiVergara ?

https://github.com/Laboratoria/bootcamp/commit/4b2b59cca91cc05c87563959492245f2dd6865f3

**Comment by DeysiVergara** [comment]
Concuerdo, nos quedamos con renderItems, haré el cambio en la implementación.

**Comment by DeysiVergara** [comment]
https://github.com/Laboratoria/impl-dev-data-lovers/pull/25
