### ISSUE TITLE
Aplicamos tests de OAs en Data Lovers

### ISSUE THREAD

**Issue by unjust** [Laboratoria/impl-dev-data-lovers#2]
[Original #1473](https://github.com/Laboratoria/bootcamp/issues/1473)

Como [los tests en Text Analyzer](https://github.com/Laboratoria/bootcamp/tree/main/projects/01-text-analyzer/read-only/test/oa) hacemos tests de OAs, usando la implementacion de https://github.com/Laboratoria/bootcamp/issues/1471.

Relacionado a https://github.com/Laboratoria/bootcamp/issues/1446

Podemos ver https://astexplorer.net/ y no se si podemos usar algo similar de Copilot.

**Comment by unjust** [comment]
> 1. Uso de HTML semántico
* `<h1>` uniqo y `<h2>` ?
* `<select>` con `<label>`
* `<ul>` o `<ol> para los items
* agregamos lighthouse como github action?
> 2. Uso de selectores de CSS
* hay selectores class
* un selector se llama card?
> 3. Modelo de caja (box model): borde, margen, padding
> 4. Uso de flexbox en CSS
* uso de flexbox en sentido row y column 
* uso de flexbox para el container de los cards
* uso de flexbox para bar de UI inputs
> 5. Uso de selectores del DOM
* `querySelector` para elegir `select` con `name` (selector attributo)
> 6. Manejo de eventos del DOM (listeners, propagación, delegación)
* `addEventListener` con uso de `e.target` o `e.currentTarget`
> 7. Manipulación dinámica del DOM
> 8. Diferenciar entre tipos de datos primitivos y no primitivos
> 9. Arrays (arreglos)
* metodos `map`, `filter`, `reduce`
* no uso de `forEach` cuando mejor `map` ?
> 10. Objetos (key, value)
* notacion de punto
* notacion de brackets
> 11. Variables (declaración, asignación, ámbito)
* el linter resalta eso?
> 12. Uso de condicionales (if-else, switch, operador ternario, lógica booleana)
> 13. Uso de bucles/ciclos (while, for, for..of)
* preferimos `forEach` en este proyecto?
> 14. Funciones (params, args, return)
> 15. Pruebas unitarias (unit tests)
> 16. Módulos de ECMAScript (ES Modules)
> 17. Uso de linter (ESLINT)
> 18. Uso de identificadores descriptivos (Nomenclatura y Semántica)
> 19. Diferenciar entre expresiones (expressions) y sentencias (statements)
* return de un expresion en lugar de if return true else return false?
> 20. Git: Instalación y configuración
> 21. Git: Control de versiones con git (init, clone, add, commit, status, push, pull, remote)
> 22. Git: Integración de cambios entre ramas (branch, checkout, fetch, merge, reset, rebase, tag)
> 23. GitHub: Creación de cuenta y repos, configuración de llaves SSH
> 24. GitHub: Despliegue con GitHub Pages
> 25. GitHub: Colaboración en Github (branches | forks | pull requests | code review | tags)
> 26. Diseñar y desarrollar un producto o servicio poniendo a las usuarias en el centro
> 27. Crear prototipos de alta fidelidad que incluyan interacciones (no sabia que DL incluye eso)
> 28. Seguir los principios básicos de diseño visual
> 29. Planear y ejecutar testeos de usabilidad de prototipos en distintos niveles de fidelidad

**Comment by ssinuco** [comment]
Mis comentarios:

1. Uso de HTML semántico

No haria mucho push en probar este OA. Verificar el uso de  h1, h2, que el selet tenga un label y el uso de ul o ol, suena bien pero tampoco me parce tan necesario. Tampoco agregaria lighthouse porque aumentaria el scope del proyecto y si se hace deberia mencionarse algo en el README.

2. Uso de selectores de CSS

Aqui yo validaria el uso de combinadores CSS, por ejemplo:
[Adjacent or next sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator)
[Child combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator)
[Column combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Column_combinator)
[General or subsequent sibling combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator)
[Descendant combinator](https://developer.mozilla.org/en-US/docs/Web/CSS/Descendant_combinator)
[Namespace separator](https://developer.mozilla.org/en-US/docs/Web/CSS/Namespace_separator)
    
3. Modelo de caja (box model): borde, margen, padding

Misma prueba que hay en Text Analyzer. Verificar que el css use atributos del modelo de caja.

4. Uso de flexbox en CSS

De acuerdo con los propuestos

5. Uso de selectores del DOM

Verificar que las estudiantes no se queden solo usando getElementById. Haria un prueba que valide que uso de los siguientes selectores solo con el objetivo que las estudiantes exploren otras alternativas

[querySelector()](https://developer.mozilla.org/es/docs/Web/API/Document/querySelector)
[getElementsByClassName()](https://developer.mozilla.org/es/docs/Web/API/Document/getElementsByClassName)
[getElementsByName()](https://developer.mozilla.org/es/docs/Web/API/Document/getElementsByName)
[getElementsByTagName()](https://developer.mozilla.org/es/docs/Web/API/Document/getElementsByTagName)
[getElementsByTagNameNS()](https://developer.mozilla.org/es/docs/Web/API/Document/getElementsByTagNameNS)

6. Manejo de eventos del DOM (listeners, propagación, delegación)

En este proyecto se puede usar [Event Bubbling](https://www.freecodecamp.org/news/event-bubbling-in-javascript/) pero las estudiantes nunca lo hacen. Seria muy chevere que se escribiera una prueba para probar que el codigo hace uso de este concepto. La preguntas es cómo....

7. Manipulación dinámica del DOM

Agregaria a lo propuesto verificar el uso de createElement y appendChild

9. Arrays (arreglos)

De acuerdo con lo propuesto.  Respecto a  _no uso de forEach cuando mejor map ?_ creo que no es posible hacer una prueba de analisis estatico que determine de esto.

10. Objetos (key, value)

De acuerdo

11. Variables (declaración, asignación, ámbito)

Creo que se puede configurar el Linter para que advierta el uso de var y otras malas practicas en variables

13. Uso de bucles/ciclos (while, for, for..of)

Mmm creo que se puede escribir una prueba para determinar si se esta usando un for para recorrer un arreglo, en ese caso lanzar error para recomendar forEach.

19. Diferenciar entre expresiones (expressions) y sentencias (statements)

Creo que se puede configurar el Linter para validar lo que propones.

**Comment by unjust** [comment]
Una sintesis de mis y Sergios comentarios
@DeysiVergara tienes algo para agregar?

https://gist.github.com/unjust/523e3bebc69c10766750d2b15a9868b5
