### ISSUE TITLE
Cambios a test OAs html, README OAs html

### ISSUE THREAD

**Issue by unjust** [Laboratoria/impl-dev-data-lovers#20]
https://docs.google.com/document/d/1dAFmF-1kxlUyp3HDD9U-RWOt84z8r6Wlqrrz8HxuDKw/edit

* [x] Al correr los tests el primer error que sale es porque no encuentra renderView. Revisando el archivo oa-html.spec.js efectivamente lo que se importa es renderItems y no renderView. Realizando este cambio, se pueden ejecutar los tests.

* El test indica que se debe tener un footer, pero el readme no lo especifica (@unjust va aa ser esto en el readme)

* [x] En el mismo archivo de test, está pasando el describe de select sin que en mi HTML exista un `<select>`. Hice las pruebas modificando el test y usando una etiqueta `<a>` en el querySelectorAll y sigue pasando esos tests. 

* [x] Lo mismo sucede para el describe de `<ul>`. No hay `<ul>` en .html y en este punto aún no se agrega de forma dinámica.

* [x] Por otro lado, se está importando la función renderItems, pero no se está testeando elementos de ese template. Entonces, ¿Es posible prescindir de la importación del renderItems? 

* [x] O en caso de permanencia ¿Es posible agregar tests que involucren el itemscope, itemprop, itemtype?

* [x] No me hace mucho sentido el form como parte del checklist si este no está especificado antes en el punto 3 (funcionalidades). (@unjust va a ser esto en el readme, quitamos el `<form>` para encontrar su manera limpiar los filtros)

**Comment by DeysiVergara** [comment]
Ya  corregí los errores del select. https://github.com/Laboratoria/impl-dev-data-lovers/pull/25. Sumaré algunos tests mas mañana.
